### ISSUE TITLE
Add support for receiving kernel audit messages

### ISSUE THREAD

**Issue by andrewkroh** [elastic/gosigar#65]
This library already has other netlink code, so adding support for receiving audit messages from the kernel over netlink shouldn't take a large effort. But parsing and enriching the data will take more effort.

- [x] Add an `audit_set_pid` function to register our process with the kernel to receive events. #66
- [x] Add a function for receiving events. #66
- [x] Add the ability to parse the key/value data from the string. #68
- [x] Enrich data with table lookups (e.g. arch to name, syscall to name, hex decoding, sockaddr decoding, etc.). #68
- [x] Add functions for enabling audit, setting the rate limit, and setting the backlog limit. #69 
- [ ] Add the ability to detect dropped events.
- [ ] Add a mechanism to set rules (either natively or by executing `auditctl`).
- [ ] Add UID enrichment.

**Comment by andrewkroh** [comment]
The audit code is moving to [github.com/elastic/go-libaudit](https://github.com/elastic/go-libaudit) where it will have better visibility as a library.
